events {}

http {

    upstream student_api {
        server api1:8080;
        server api2:8080;
    }

    server {
        listen 8080;

        location / {
            proxy_pass http://student_api;
        }
    }

}
